version: '3'

services:
  goapp:
    container_name: goapp
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: sh -c "cd src && go run main.go"
    depends_on:
      mysql:
        condition: service_healthy
  


  mysql: 
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routes
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 3
   
 
