version: '3.2'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "$UID:$GID"
    ports:
      - "9090:9090"
    volumes:
      - ./../.docker/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./../.docker/grafana_data:/var/lib/grafana
